/*===================================================================================================================================
 * @file    Port_PBcfg.h
 * @version 1.0.0
 * @brief   AUTOSAR Port Post-Build Configuration header.
 * @details Port driver post-build configuration header file for S32K144EVB Microcontroller
 * @project AUTOSAR 4.4.0 MCAL
 * @platform ARM
 * @peripheral S32K144EVB
 * @autosar_version 4.4.0
 * @autosar_revision ASR_REL_4_0.REV_0000
 * @sw_version 1.0.0
 * @autor  ABDALLAH MOHAMED
 * @addtogroup  Port
====================================================================================================================================*/

/*===================================================================================================================================
 * Project : AUTOSAR 4.4.0 MCAL
 * Platform : ARM
 * Peripheral : S32K144EVB
 * Autosar Version : 4.4.0
 * Autosar Revision: ASR_REL_4_0.REV_0000
 * Sw Version  : 1.0.0
====================================================================================================================================*/
#ifndef PORT_PBCFG_H_
#define PORT_PBCFG_H_

/*=================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
=================================================================================================*/
#include "Port.h"




/*=================================================================================================
*                              SOURCE FILE VERSION INFORMATION
=================================================================================================*/

/*Module Version 1.0.0*/
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*AUTOSAR Version 4.0.3*/
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION      (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION      (4U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION      (0U)


/*=================================================================================================
*                                     FILE VERSION CHECKS
=================================================================================================*/

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif



const Port_ConfigType Port_Configuration[] = {
    /* Port A Configuration (PTA0 - PTA17) */
    {PORT_PORTA_ID, PORT_PIN0_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN1_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN2_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN3_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN4_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN5_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN6_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN7_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN8_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN9_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN10_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN11_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN12_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN13_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN14_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN15_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN16_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN17_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},

    /* Port B Configuration (PTB0 - PTB17) */
    {PORT_PORTB_ID, PORT_PIN0_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN1_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN2_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN3_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN4_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN5_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN6_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN7_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN8_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN9_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN10_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN11_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN12_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN13_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN14_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN15_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN16_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN17_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},

    /* Port C Configuration (PTC0 - PTC17) */
    {PORT_PORTC_ID, PORT_PIN0_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN1_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN2_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN3_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN4_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN5_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN6_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN7_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN8_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN9_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN10_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN11_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN12_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN13_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN14_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN15_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN16_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN17_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},

    /* Port D Configuration (PTD0 - PTD17) */
    {PORT_PORTD_ID, PORT_PIN0_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN1_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN2_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN3_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN4_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN5_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN6_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN7_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN8_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN9_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN10_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN11_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN12_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN13_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN14_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN15_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN16_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN17_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},

    /* Port E Configuration (PTE0 - PTE16) */
    {PORT_PORTE_ID, PORT_PIN0_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN1_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN2_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN3_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN4_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN5_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN6_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN7_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN8_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN9_ID,  PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN10_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN11_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN12_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN13_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN14_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN15_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN16_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
};
#endif /* PORT_PBCFG_H_ */
