/*===================================================================================================================================
 * @file    Port_PBcfg.c
 * @version 1.0.0
 * @brief   AUTOSAR Port Post-Build Configuration source.
 * @details Port driver post-build configuration array definition for S32K144EVB.
 * @project AUTOSAR 4.4.0 MCAL
 * @platform ARM
 * @peripheral S32K144EVB
 * @autosar_version 4.4.0
 * @autosar_revision ASR_REL_4_0.REV_0000
 * @sw_version 1.0.0
 * @author  ABDALLAH MOHAMED
====================================================================================================================================*/

/*===================================================================================================================================
 * Project : AUTOSAR 4.4.0 MCAL
 * Platform : ARM
 * Peripheral : S32K144EVB
 * Autosar Version : 4.4.0
 * Autosar Revision: ASR_REL_4_0.REV_0000
 * Sw Version  : 1.0.0
====================================================================================================================================*/

/*=================================================================================================
*                                      INCLUDES
=================================================================================================*/
#include "Port.h"
#include "Port_PBcfg.h"

/*=================================================================================================
*                         SOURCE FILE VERSION INFORMATION
=================================================================================================*/
#define PORT_PBCFG_C_VENDOR_ID                      (43U)

#define PORT_PBCFG_C_AR_RELEASE_MAJOR_VERSION       (4U)
#define PORT_PBCFG_C_AR_RELEASE_MINOR_VERSION       (4U)
#define PORT_PBCFG_C_AR_RELEASE_PATCH_VERSION       (0U)

#define PORT_PBCFG_C_SW_MAJOR_VERSION               (1U)
#define PORT_PBCFG_C_SW_MINOR_VERSION               (0U)
#define PORT_PBCFG_C_SW_PATCH_VERSION               (0U)

/*=================================================================================================
*                           FILE VERSION CHECKS
=================================================================================================*/
/* Check if Port_PBcfg.c and Port.h are of the same vendor */
#if (PORT_PBCFG_C_VENDOR_ID != PORT_VENDOR_ID)
    #error "Port_PBcfg.c and Port.h have different vendor ids"
#endif

/* Check if Port_PBcfg.c and Port.h are of the same AUTOSAR version */
#if ((PORT_PBCFG_C_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION) || \
     (PORT_PBCFG_C_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION) || \
     (PORT_PBCFG_C_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
    #error "AutoSar Version Numbers of Port_PBcfg.c and Port.h are different"
#endif

/* Check if Port_PBcfg.c and Port.h are of the same Software version */
#if ((PORT_PBCFG_C_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION) || \
     (PORT_PBCFG_C_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION) || \
     (PORT_PBCFG_C_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
    #error "Software Version Numbers of Port_PBcfg.c and Port.h are different"
#endif
/*=================================================================================================
*                                GLOBAL CONSTANTS DEFINITION
=================================================================================================*/

#define PORT_START_SEC_CONFIG_DATA_UNSPECIFIED
/** @violates @ref PORT_PBCFG_C_REF_1 Precautions to prevent the contents of a header file being included twice */
#include "Port_MemMap.h"

static const Port_PinConfigType Port_Pins_Array[PORT_CONFIGURED_PINS] = {
    /* Port A Configuration (PTA0 - PTA17) */
    {PORT_PORTA_ID, PORT_PIN0_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN1_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN2_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN3_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN4_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN5_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN6_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN7_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN8_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN9_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN10_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN11_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN12_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN13_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN14_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN15_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN16_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTA_ID, PORT_PIN17_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},

    /* Port B Configuration (PTB0 - PTB17) */
    {PORT_PORTB_ID, PORT_PIN0_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN1_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN2_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN3_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN4_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN5_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN6_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN7_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN8_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN9_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN10_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN11_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN12_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN13_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN14_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN15_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN16_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTB_ID, PORT_PIN17_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},

    /* Port C Configuration (PTC0 - PTC17) */
    {PORT_PORTC_ID, PORT_PIN0_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN1_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN2_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN3_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN4_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN5_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN6_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN7_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN8_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN9_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN10_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN11_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN12_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN13_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN14_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN15_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN16_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTC_ID, PORT_PIN17_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},

    /* Port D Configuration (PTD0 - PTD17) */
    {PORT_PORTD_ID, PORT_PIN0_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN1_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN2_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN3_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN4_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN5_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN6_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN7_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN8_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN9_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN10_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN11_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN12_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN13_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN14_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN15_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN16_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTD_ID, PORT_PIN17_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},

    /* Port E Configuration (PTE0 - PTE16) */
    {PORT_PORTE_ID, PORT_PIN0_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN1_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN2_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN3_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN4_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN5_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN6_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN7_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN8_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN9_ID,  PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN10_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN11_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN12_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN13_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN14_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN15_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
    {PORT_PORTE_ID, PORT_PIN16_ID, PORT_PIN_IN, PORT_PIN_RESISTOR_OFF, PORT_PIN_MODE_DIO, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_LEVEL_LOW},
};



const Port_ConfigType Port_Configuration = {
    Port_Pins_Array,        /* Pointer to the array above */
    PORT_CONFIGURED_PINS    /* The size of the array */
};

#define PORT_STOP_SEC_CONFIG_DATA_UNSPECIFIED
/** @violates @ref PORT_PBCFG_C_REF_1 Precautions to prevent the contents of a header file being included twice */
#include "Port_MemMap.h"